# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-03 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('Contributors', models.ManyToManyField(blank=True, related_name='contributor', to=settings.AUTH_USER_MODEL)),
                ('Event_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
