# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bday_App_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('pic', models.URLField()),
                ('facebook_id', models.CharField(blank=True, max_length=200)),
                ('google_plus_id', models.CharField(blank=True, max_length=200)),
                ('bday_app_friends', models.ManyToManyField(related_name='_bday_app_user_bday_app_friends_+', to='bday_user.Bday_App_User')),
            ],
        ),
        migrations.CreateModel(
            name='Non_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pic', models.URLField()),
                ('facebook_id', models.CharField(blank=True, max_length=200)),
                ('google_plus_id', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bday_app_user',
            name='non_bday_app_friends',
            field=models.ManyToManyField(to='bday_user.Non_User'),
        ),
        migrations.AddField(
            model_name='bday_app_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
