# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bday_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bday_app_user',
            name='bday_app_friends',
        ),
        migrations.RemoveField(
            model_name='bday_app_user',
            name='non_bday_app_friends',
        ),
        migrations.AddField(
            model_name='bday_app_user',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bday_app_user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_bday_app_user_friends_+', to='bday_user.Bday_App_User'),
        ),
        migrations.AlterField(
            model_name='bday_app_user',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Non_User',
        ),
    ]
