# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bday_user', '0002_auto_20160701_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='bday_app_user',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bday_app_user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bday_app_user',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bday_app_user',
            name='pic',
            field=models.URLField(blank=True),
        ),
    ]
