# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bday_user', '0005_auto_20160701_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='bday_app_user',
            name='profile_type',
            field=models.CharField(choices=[('F', 'facebook'), ('G', 'google')], max_length=2, null=True),
        ),
    ]
